package com.github.sanctuscorvus

enum class SafetyCategory(val value: String) {
    HARM_CATEGORY_HARASSMENT("HARM_CATEGORY_HARASSMENT"),
    HARM_CATEGORY_HATE_SPEECH("HARM_CATEGORY_HATE_SPEECH"),
    HARM_CATEGORY_SEXUALLY_EXPLICIT("HARM_CATEGORY_SEXUALLY_EXPLICIT"),
    HARM_CATEGORY_DANGEROUS_CONTENT("HARM_CATEGORY_DANGEROUS_CONTENT"),
    HARM_CATEGORY_CIVIC_INTEGRITY("HARM_CATEGORY_CIVIC_INTEGRITY")
}